name: "Runner CI Python Tests"
description: "Runner CI Python Tests"
inputs:
  module-name:
    required: true
  module-folder:
    required: true
outputs:
  coverage-paths:
    description: "Coverage Paths"
    value: ${{ steps.build-coverage-reports.outputs.coverage-paths }}
  linter-reports:
    description: "Linter Options"
    value: ${{ steps.build-linter-reports.outputs.linter-reports }}
  mypy-logs:
    description: "MyPy Logs"
    value: ${{ steps.build-linter-reports.outputs.mypy-logs }}
  black-diff:
    description: "Black Diff"
    value: ${{ steps.build-linter-reports.outputs.black-diff }}
  isort-diff:
    description: "Isort Diff"
    value: ${{ steps.build-linter-reports.outputs.isort-diff }}
runs:
  using: "composite"
  steps:
    - name: Build Coverage Reports
      id: build-coverage-reports
      shell: bash
      working-directory: ${{ inputs.module-folder }}
      run: |
         virtualenv .venv
         source .venv/bin/activate
         JSON_CONFIG='{"module": "${{ inputs.module-name }}", "folder": "${{ inputs.module-folder }}", "lang": "py"}'
         REPORT_FOLDER=reports
         ci_build_checkers_reports --venv_folder .venv --output_folder "${REPORT_FOLDER}" "${JSON_CONFIG}" --print_commands pycoverage | while read cmd
         do
           echo "CMD: ${cmd}"
           eval ${cmd}
         done
         rm -rf .venv
         echo "::set-output name=coverage-paths::${REPORT_FOLDER}/coverage.xml"

    - name: Build Linter Reports
      id: build-linter-reports
      shell: bash
      working-directory: ${{ inputs.module-folder }}
      run: |
         # rm -rf .venv
         virtualenv .venv
         source .venv/bin/activate
         JSON_CONFIG='{"module": "${{ inputs.module-name }}", "folder": "${{ inputs.module-folder }}", "lang": "py"}'
         REPORT_FOLDER=reports
         mkdir -p ${REPORT_FOLDER}
         ci_build_checkers_reports --venv_folder .venv --output_folder "${REPORT_FOLDER}" "${JSON_CONFIG}" --print_commands mypy,flake,black,isort | while read cmd
         do
           echo "CMD: ${cmd}"
           eval ${cmd}
         done
         rm -rf .venv
         echo "::set-output name=mypy-logs::${REPORT_FOLDER}/mypy.log"
         echo "::set-output name=black-diff::${REPORT_FOLDER}/black.diff"
         echo "::set-output name=black-isort::${REPORT_FOLDER}/isort.diff"
         echo "::set-output name=linter-reports::-Dsonar.python.flake8.reportPaths=${REPORT_FOLDER}/flake.txt"


