name: "Runner CI Python Tests"
description: "Runner CI Python Tests"
inputs:
  module-name:
    required: true
  module-folder:
    required: true
outputs:
  coverage-paths:
    description: "Coverage Paths"
    value: ${{ steps.build-coverage-reports.outputs.coverage-paths }}
  linter-reports:
    description: "Linter Options"
    value: ${{ steps.build-linter-reports.outputs.linter-reports }}

runs:
  using: "composite"
  steps:
    - name: Build Coverage Reports
      id: build-coverage-reports
      shell: bash
      working-directory: ${{ inputs.module-folder }}
      run: |
         virtualenv .venv
         source .venv/bin/activate
         JSON_CONFIG='{"module": "${{ inputs.module-name }}", "folder": "${{ inputs.module-folder }}", "lang": "py"}'
         REPORT_FOLDER=reports_${RANDOM}
         ci_build_checkers_reports --venv_folder .venv --output_folder "${REPORT_FOLDER}" "${JSON_CONFIG}" --print_commands pycoverage | while read cmd
         do
           echo "CMD: ${cmd}"
           eval ${cmd}
         done
         rm -rf .venv
         echo "::set-output name=coverage-paths::${REPORT_FOLDER}/coverage.xml"

    - name: Build Linter Reports
      id: build-linter-reports
      shell: bash
      working-directory: ${{ inputs.module-folder }}
      run: |
         # rm -rf .venv
         virtualenv .venv
         source .venv/bin/activate
         JSON_CONFIG='{"module": "${{ inputs.module-name }}", "folder": "${{ inputs.module-folder }}", "lang": "py"}'
         REPORT_FOLDER=reports_${RANDOM}
         mkdir -p ${REPORT_FOLDER}
         ci_build_checkers_reports --venv_folder .venv --output_folder "${REPORT_FOLDER}" "${JSON_CONFIG}" --print_commands mypy,flake | while read cmd
         do
           echo "CMD: ${cmd}"
           eval ${cmd}
         done
         rm -rf .venv
         cat ${REPORT_FOLDER}/mypy_junit.xml
         echo "::set-output name=linter-reports::-Dsonar.python.flake8.reportPaths=${REPORT_FOLDER}/flake.txt -Dsonar.junit.reportPaths=${REPORT_FOLDER}/mypy_junit.xml"


