name: Sonar Scan
on:
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:

  detect-changes:
    name: Detect Changed Modules
    timeout-minutes: 5
    runs-on: ubuntu-latest
    outputs:
      changed-modules: ${{ steps.detect-changed-modules.outputs.changed-modules }}
    steps:
      - name: Checkout Airbyte
        uses: actions/checkout@v2
        with:
          fetch-depth: 1000
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Intall Requirements
        run: pip install ./tools/ci_static_check_reports
      - name: Detect Changed Modules
        id: detect-changed-modules
        run: |
          git fetch
          CHANGES=$(ci_detect_changed_modules $(git diff --name-only $(git merge-base HEAD origin/master)) | jq -c .)
          echo "::set-output name=changed-modules::{ \"include\": $CHANGES }"

  run-ci-tests:
    needs: detect-changes
    name:  Tests for ${{ matrix.module }}
    runs-on: ubuntu-latest
    environment: more-secrets
    # this option must be uncommented for github env
    strategy:
      matrix: ${{fromJson(needs.detect-changes.outputs.changed-modules)}}
    env:
      MODULE_NAME: ${{ matrix.module }}
      MODULE_LANG: ${{ matrix.lang }}
      MODULE_FOLDER: ${{ matrix.folder }}
      ENV_NAME: "github"
#    # these for local dev
#    env:
#      MODULE_NAME: connectors/source-s3
#      MODULE_LANG: py
#      MODULE_FOLDER: "path2"
#      ENV_NAME: "local"

    steps:
    - name: Print Settings
      run: |
         echo "Module: ${{ env.MODULE_NAME }}, Lang: ${{ env.MODULE_LANG }}, Folder: ${{ env.MODULE_FOLDER }}"
    - name: Checkout Airbyte
      if: ${{ env.ENV_NAME == 'github' }}
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Run Tests Runner
      id: run-python-tests
      uses: ./.github/actions/ci-tests-runner
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        module-name: ${{ env.MODULE_NAME }}
        module-folder: ${{ env.MODULE_FOLDER }}
        module-lang: ${{ env.MODULE_LANG }}
        sonar-token: ${{ secrets.SONAR_TOKEN }}
        sonar-host: ${{ secrets.SONAR_HOST_URL }}
        pull-request-id: "${{ github.repository }}/${{ github.event.pull_request.number }}"
        remove-sonar-project: ${{ github.event_name == 'pull_request' && github.event.action == 'closed' }}



